//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public HOADON()
        {
            this.PHIEUTHUTIENs = new HashSet<PHIEUTHUTIEN>();
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public int MAHOADON { get; set; }
        public System.DateTime NGAYLAP { get; set; }
        public string MAKHACHHANG { get; set; }
        public decimal TONGTIEN { get; set; }
    
        public virtual ICollection<PHIEUTHUTIEN> PHIEUTHUTIENs { get; set; }
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
