//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.PHIEUTHUTIENs = new HashSet<PHIEUTHUTIEN>();
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string MAKHACHHANG { get; set; }
        public string TENKHACHHANG { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
        public string DIENTHOAI { get; set; }
    
        public virtual ICollection<PHIEUTHUTIEN> PHIEUTHUTIENs { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
