//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUTIEN
    {
        public int MAPHIEUTHU { get; set; }
        public int MAHOADON { get; set; }
        public string MAKHACHHANG { get; set; }
        public System.DateTime NGAYTHU { get; set; }
        public decimal SOTIENTHU { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
